### ISSUE TITLE
ANSI Color escape characters not handled properly on Elm 0.16.0

### ISSUE THREAD

**Issue by pdamoc** [deadfoxygrandpa/Elm.tmLanguage#51]
The new error messages in Elm 0.16.0 produce an error that looks like this:

![6d39b9ae-7b07-11e5-9cb5-ee2ac23d2362](https://cloud.githubusercontent.com/assets/878106/10725300/afd01f0c-7bd3-11e5-8132-33fe799c57f5.png)

I have reported this as an issue on elm-compiler and Evan said it is related to the Sublime Plugin not handling ANSI escape characters properly. 

Looking at [this stackoverflow answer](http://stackoverflow.com/questions/8484167/ansi-color-in-git-is-not-displayed-correctly) I think that it might be ANSI color escape characters.

**Comment by pdamoc** [comment]
The following repository might have some code that could solve this. 
https://github.com/aziz/SublimeANSI

**Comment by dnalot** [comment]
Can you link the issue? We could fix it but we're consuming the API for tooling authors. Ultimately @evancz should JSON sanitized of console artifacts like color sequences. Unless @deadfoxygrandpa disagrees I recommend leaving it to the compiler. PRs welcome (CC @rtfeldman).

**Comment by evancz** [comment]
`elm-make` checks to see [if it is printing to the terminal or not](https://github.com/elm-lang/elm-make/blob/master/src/Report.hs#L35), and it only prints colors if it is going to the terminal. Otherwise there should be no escape characters. Furthermore, when creating JSON, it should just be producing strings.

If you are reading from terminal somehow, then the bug is here. If it is reading from JSON then there is something freaky going on in elm-compiler or elm-make that I have not observed yet.

**Comment by dnalot** [comment]
Thanks for the explanation I'll look :+1:

**Comment by pdamoc** [comment]
Fixed in latest version.

**Comment by fbonetti** [comment]
I'm still seeing this issue. Is anyone else having this problem? Here's my environment:

* Elm Language Support v0.16.3
* Elm Platform v0.16.0
* OS X Yosemite v10.10.1

<img width="695" alt="screen shot 2016-02-11 at 9 49 01 am" src="https://cloud.githubusercontent.com/assets/2244354/12981058/be03cc4c-d0a4-11e5-9f51-082f2acd43b2.png">
